name: flutter_redurx
version: 1.1.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  redurx:
    git:
      url: https://github.com/wrbl606/ReduRx.git
      ref: "d817cf3afeae4d6fb4b2fc0deac03fa861b6860c"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
